//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.BotReply = new HashSet<BotReply>();
        }
    
        public int AnswerId { get; set; }
        public int IntentId { get; set; }
        public string Answer1 { get; set; }
        public Nullable<bool> TrainedAnswer { get; set; }
        public Nullable<int> TrainedAnswerId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Intent Intent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BotReply> BotReply { get; set; }
        public virtual TrainedAnswer TrainedAnswer1 { get; set; }
    }
}
