//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int EntityId { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
        public int IntentId { get; set; }
    
        public virtual Intent Intent { get; set; }
    }
}
